Handle edge-cases in gencerts
Make sure that we exit with success if the files already exist and
that we exit with failure and a message if only one or the other
is present.

diff --git a/httpd-ssl-gencerts b/httpd-ssl-gencerts
--- a/httpd-ssl-gencerts
+++ b/httpd-ssl-gencerts
@@ -4,10 +4,23 @@ set -e
 
 FQDN=`hostname`
 
-if test -f /etc/pki/tls/certs/localhost.crt -o \
+if test -f /etc/pki/tls/certs/localhost.crt -a \
         -f /etc/pki/tls/private/localhost.key; then
+    exit 0
+fi
+
+if test -f /etc/pki/tls/certs/localhost.crt -a \
+        ! -f /etc/pki/tls/private/localhost.key; then
+    echo "Missing certificate key!"
     exit 1
 fi
+
+if test ! -f /etc/pki/tls/certs/localhost.crt -a \
+         -f /etc/pki/tls/private/localhost.key; then
+    echo "Missing certificate, but key is present!"
+    exit 1
+fi
+
 
 sscg -q                                                             \
      --cert-file           /etc/pki/tls/certs/localhost.crt         \
